import numpy as np

occupation_map = {
    # student variants
    "student": "student",
    "student m": "student",
    "student rn": "student",
    "student we": "student",
    "as student": "student",
    "student right now": "student",
    "i'm a student": "student",
    "i am a student": "student",
    "i am an student": "student",
    "bachelor student": "student",
    "bachelor's student": "student",
    "student (still studying)": "student",
    "currently studying": "student",
    "studying right now": "student",
    "studying": "student",
    "study": "student",
    "engineering student": "student",
    "it student": "student",
    "architect student": "student",
    "work as a student": "student",
    "iam undergraduate student": "student",
    "student{ ioe pulchowk campus, computer engineering}": "student",
    "student{ioe pulchowk campus, computer engineering)": "student",
    "student, web3 dev": "student",
    "youth educator and an it student": "student",
    "student and housewife": "student",
    "student and teaching": "student",
    "studenr": "student",
    "studient": "student",
    "my occupation is a student": "student",
    "nothing i am a student": "student",
    "student now": "student",
    "student /entrepreneur": "student",
    "student (undergraduate engineer)": "student",
    "not working yet, student": "student",
    "currently i am student pursuing bachelor degree on civil engineering": "student",
    "student but also a genai engineering intern": "student",
    "csit": "student",
    "csit(student)": "student",
    "student and tutor": "student",
    "i am a student, bro": "student",
    "i am an undergraduate student": "student",
    "educational youtuber and student": "student",
    "learning": "student",
    "ca student": "student",
    "undergraduate student": "student",
    "im a student": "student",

    # unemployed / no occupation
    "unemployed": "unemployed",
    "not working": "unemployed",
    "no occupation": "unemployed",
    "i dont work right now": "unemployed",
    "i don't work right now": "unemployed",
    "nothing": "unemployed",
    "null": "unemployed",
    "not": "unemployed",
    "not yet working": "unemployed",
    "job": "unemployed",  # ambiguous/no-info, treat as unusable/unclear
    "no": "unemployed",
    "no occupation till now": "unemployed",
    "not employed yet": "unemployed",
    "not done yet": "unemployed",
    "na": "unemployed",
    "berojgar": "unemployed",  # Nepali for "unemployed"
    "jobless": "unemployed",
    "not yet": "unemployed",
    "right now nothing": "unemployed",

    # teaching
    "teacher": "teacher",
    "teaching": "teacher",
    "education learning": "teacher",
    "tutor": "teacher",
    "part time teacher": "teacher",

    # engineering / tech
    "engineering": "engineering/tech",
    "software engineer": "engineering/tech",
    "software engineering": "engineering/tech",
    "electrical engineer": "engineering/tech",
    "civil engineer": "engineering/tech",
    "developer": "engineering/tech",
    "junior machine learning engineer": "engineering/tech",
    "data analyst": "engineering/tech",
    "data management specialist": "engineering/tech",
    "cybersecurity analyst": "engineering/tech",
    "security": "engineering/tech",
    "seecurity operation": "engineering/tech",
    "security operation": "engineering/tech",
    "frontend developer": "engineering/tech",
    "quality assurance analyst": "engineering/tech",
    "bss noc analyst": "engineering/tech",
    "data scientist/oyo corper": "engineering/tech",
    "web developer": "engineering/tech",
    "computer engineer": "engineering/tech",
    "etl associate": "engineering/tech",
    "data scientist": "engineering/tech",
    "engineer": "engineering/tech",
    "data science intern": "engineering/tech",

    # management/business
    "ceo": "management/business",
    "digital project manager": "management/business",
    "office manager": "management/business",
    "brand manager": "management/business",
    "opd coordinator": "management/business",
    "shipping coordinator": "management/business",
    "entrepreneur": "management/business",
    "enterpreneur": "management/business",
    "business": "management/business",
    "employee": "management/business",
    "banking sector": "management/business",
    "accounting": "management/business",
    "printing": "management/business",
    "part time job": "management/business",
    "auditors": "management/business",
    "accountant": "management/business",
    "supervisor": "management/business",

    # medical
    "doctor": "medical",
    "nurse": "medical",
    "nursing": "medical",
    "pharmacist": "medical",
    "becoming ayurvedic doctor": "medical",

    # misc professional / other
    "i'm a team leader in customer service": "other",
    "research intern": "other",
    "researcher": "other",
    "social worker": "other",
    "counsellor": "other",
    "self employed": "other",
    "self-employed": "other",
    "graphic designer": "other",
    "graphics designer and video editor": "other",
    "architect": "other",
    "customer service representative": "other",
    "freelancer and network marketer": "other",
    "video editor": "other",
    "graphic and product designer": "other",
    "aviation safety officer": "other",
    "sales assistant": "other",
    "sales": "other",
}

ethnicity_map = {
    "asian" : "asian",
    "african" : "african",
    "american indian" : "other",
    "latino" : "other",
    "nepali" : "asian",
    "black african/african american" : "african",
    "indian" : "asian",
    "bramin" : "asian",
    "nepalses" : "asian",
    "hispanic" : "other",
    "indo aryan" : "other",
    "info-aryan" : "other",
    "khas-arya" : "other",
    "aryan" : "other",
}

language_map = {
    "english": "english", "little bit english" : "english", "little" : "english", "bit" : "english",
    "hindi": "hindi", "hindni": "hindi",
    "arabic": "global", "arebic": "global",
    "bajika": "south_asian_other",
    "bhojpuri": "south_asian_other", "bojpuri": "south_asian_other",
    "chinese": "global",
    "dotali": "nepali_dominant", "doteli": "nepali_dominant",
    "efik": "african_other",
    "ekoi": "african_other",
    "french": "global",
    "greek": "global",
    "gurung": "nepali_dominant",
    "hausa": "african_other",
    "ibibio": "african_other",
    "igbo": "african_other",
    "japanese": "global",
    "korean": "global",
    "latin": "global",
    "madheshi": "nepali_dominant",
    "magar": "nepali_dominant",
    "maithali": "south_asian_other", "maithili": "south_asian_other", "maithilils": "south_asian_other",
    "maithli": "south_asian_other", "mathali": "south_asian_other", "mathi": "south_asian_other",
    "marwadi": "south_asian_other",
    "nep": "nepali", "nepal": "nepali", "nepali": "nepali", "nepalin" : "nepali", "nepalienglish" : "nepali;english",
    "neplai": "nepali", "neplit": "nepali", "neoali": "nepali",
    "newari": "nepali_dominant",
    "pahadi": "nepali_dominant",
    "pidgin": "african_other",
    "rai": "nepali_dominant",
    "sanskrit": "nepali_dominant",
    "spanish": "global",
    "swahili": "african_other",
    "tharu": "nepali_dominant",
    "urdu": "south_asian_other",
    "yoruba": "african_other",
    "lokurr" : "african_other",
    "tapa" : "african_other",
    "and": "",
    "nah": "",
    "nil": "",
    "engine" : "",
    "(ethnic" : "",
    "tongue)" : "",
    "awadhi": "south_asian_other",
    "tamang": "nepali_dominant",
    "phadi" : "nepali_dominant",
    "telugu" : "south_asian_other",
    "bajhangi" : "nepali_dominant",
    "german" : "global",
    "ila" : "african_other",
    "tamil" : "south_asian_other",
    "finnish" : "global",
    "darchuleli" : "nepali_dominant",
}
region_map = {
    "nepal" : "nepal",
    "nigeria" : "africa_other",
    "united kingdom" : "global",
    "saudi arabia" : "asia_other",
    "united states" : "global",
    "india" : "asia_other",
    "tanzania" : "africa_other",
    "estonia" : "global",
    "qatar" : "asia_other",
    "finland" : "global",
    "thailand" : "asia_other",
}

ordinal_maps = {
    "internet_usage_frequency": {
        "never": 1,
        "yearly": 2,
        "weekly": 3,
        "seasonal": 2,
        "daily": 4,
    },
    "daily_ai_exposure": {
        "never": 1,
        "seasonal": 2,
        "monthly": 3,
        "weekly": 4,
        "daily": 5,
    },
    "computer_proficiency": {
        "not proficient i struggle with using computers and only use them when absolutely necessary, usually with assistance": 1,
        "limited proficiency i can do simple tasks with guidance, but i often need help and do not feel confident using computers independently": 2,
        "moderately proficient i can perform basic tasks like browsing the internet, sending emails, and using office software, but i may need help with more complex problems": 3,
        "proficient i am comfortable using computers for most tasks such as browsing, word processing, and using common applications i can solve minor issues on my own": 4,
        "very proficient i am highly skilled with computers, including software, internet use, and troubleshooting i can easily learn new programs and help others": 5,
    },
    "ai_familiarity": {
        "not at all familiar": 1,
        "slightly familiar": 2,
        "moderately familiar": 3,
        "very familiar": 4,
        "extremely familiar": 5,
    },
    "confidence_understanding_ai": {
        "extremely not confident": 1,
        "somewhat not confident": 2,
        "neutral": 3,
        "somewhat confident": 4,
        "extremely confident": 5,
    },
    "general_feeling_about_ai": {
        "very negative": 1,
        "somewhat negative": 2,
        "neutral": 3,
        "somewhat positive": 4,
        "very positive": 5,
    },
    "future_ai_impact": {
        "no impact": 1,
        "slight impact": 2,
        "moderate impact": 3,
        "significant impact": 4,
        "extremely significant impact": 5,
    },
    "current_ai_impact_on_daily_life": {
        "not at all": 1,
        "a little": 2,
        "somewhat": 3,
        "quite a lot": 4,
        "very much": 5,
    },
    "awareness_of_ai_usage": {
        "never": 1,
        "rarely": 2,
        "sometimes": 3,
        "often": 4,
        "always": 5,
        "i dont know": 0,
    },
    "trust_ai_healthcare": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_insurance": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_agriculture": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_finance": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_military": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_law_enforcement": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_environment": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_education": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_transportation": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_manufacturing": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_human_resources": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_remittance": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "accept_ai_hiring": {
        "not at all comfortable": 1,
        "not very comfortable": 2,
        "neutral": 3,
        "fairly comfortable": 4,
        "very comfortable": 5,
    },
    "accept_ai_energy_meter": {
        "not at all comfortable": 1,
        "not very comfortable": 2,
        "neutral": 3,
        "fairly comfortable": 4,
        "very comfortable": 5,
    },
    "support_national_ai_laws": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_voluntary_ai_certification": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_independent_ai_monitoring": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_company_self_regulation": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_ai_transparency": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_diverse_ai_development": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "trust_national_government": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_international_bodies": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_universities": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_consumer_groups": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_tech_companies": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_social_media_companies": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "support_national_ai_policies": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_ai_local_language_education": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_public_private_partnerships": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_rural_internet": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_ai_literacy": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "trust_national_government_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_local_tech_companies_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_international_ngos_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_academic_institutions_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_cooperative_societies_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_domestic_ai_more": {
        "not at all": 1,
        "not so much": 2,
        "so and so": 3,
        "somewhat": 4,
        "a lot": 5,
    },
    "perceived_ai_impact_after_survey": {
        "not at all": 1,
        "not so much": 2,
        "so and so": 3,
        "somewhat": 4,
        "a lot": 5,
    },
    "have_government_policy_to_guide_ai_development":{
        "strongly disagree": 1,
        "disagree": 2,
        "neither agree nor disagree": 3,
        "agree": 4,
        "strongly agree": 5,
    }
}

industry_map = {
    # Education
    "education": "education",
    "student": "education",
    "student in it": "education",
    "i am an student": "education",
    "student right now": "education",
    "studying": "education",
    "i am a student": "education",
    "currently the student": "education",

    # IT
    "tech": "tech",
    "it": "tech",
    "data management": "tech",
    "telecommunication": "tech",

    # Government / Public
    "public/government": "public/government",
    "government": "public/government",
    "public service": "public/government",
    "environment": "public/government",
    "ngo": "public/government",

    # Healthcare
    "healthcare": "healthcare",
    "health": "healthcare",
    "health ": "healthcare",
    "hospital": "healthcare",
    "medicine": "healthcare",
    "dentistry": "healthcare",
    "doctor": "healthcare",
    "medical": "healthcare",

    # Finance / Trade
    "finance/trade": "finance/trade",
    "financial": "finance/trade",
    "trading": "finance/trade",
    "e-commerce": "finance/trade",
    "fmcg food product import": "finance/trade",

    # Production / Manufacturing
    "production/manufacturing": "production/manufacturing",
    "manufacturing": "production/manufacturing",
    "processing": "production/manufacturing",
    "agriculture": "production/manufacturing",
    "construction": "production/manufacturing",
    "automobile": "production/manufacturing",

    # None / Other
    "none/other": "none/other",
    "engineering": "none/other",
    "engineering ": "none/other",
    "archi": "none/other",
    "architecture": "none/other",
    "transport industry": "none/other",
    "none as of right now": "none/other",
    "nothing": "none/other",
    "not working": "none/other",
    "not yet working": "none/other",
    "beauty": "none/other",
    "unemployed": "none/other",
    "civil engineering": "none/other",
    "aviation": "none/other",
    "consulting services": "none/other",
    "": "none/other",
}

app_use_ai_map = {
    "ai in agriculture" : "agriculture",
    
    "chat gpt and gemini" : "gen_ai/chatbot",
    "chat gpt, gemini etc" : "gen_ai/chatbot",
    "chatgpt, deepseek" : "gen_ai/chatbot",
    "chatgpt, meta ai" : "gen_ai/chatbot",
    "chatgpt,deepseek,gemini" : "gen_ai/chatbot",
    "chatgpt, deepseek, grok, gemini, microsoft copilot , perplexity" : "gen_ai/chatbot",
    "chatgpt" : "gen_ai/chatbot",
    "chatgpt, gemini, grok, copilot,etc" : "gen_ai/chatbot",
    "chat gpt, gemini" : "gen_ai/chatbot",
    "ai chatbots" : "gen_ai/chatbot",
    "study, research, audio video creating etc" : "gen_ai/chatbot",
    "gaming, image creation, for studies" : "gen_ai/chatbot",
    "ai assisted content creation tools" : "gen_ai/chatbot",
    "education , and ai for content generation and image creation" : "gen_ai/chatbot",
    "graphic design applications like canva" : "gen_ai/chatbot",
    "openai embeddings, llms such as chatgpt and github copilot" : "gen_ai/chatbot",
    "education deepseek" : "gen_ai/chatbot",
    "llms, designing" : "gen_ai/chatbot",
    "openai like chargpt" : "gen_ai/chatbot",
    
    "customer service chatbots" : "customer_service_chatbot",
    
    "digital payment platforms" : "digital_payment_platforms",
    "fraud detection systems" : "fraud_detection_systems",
    
    "healthcare tools" : "healthcare",
    
    "product or content recommendation systems" : "recommendation_system",
    
    "ride-hailing or delivery apps" : "product",
    
    "social media platforms using ai" : "social_media",
    
    "disaster alert systems" : "other/none",
    "ai in educations'" : "other/none",
    "no now" : "other/none",
}

ai_tools_map = {
    "calculators": "calculators",
    "calendar apps": "calendar_apps",
    "email spam filters": "email_spam_filters",
    "word processing software": "word_processing_software",

    "drones": "drones",
    "hotel booking sites": "hotel_booking_sites",
    "navigation apps": "navigation_apps",
    "ride-sharing apps": "ride_sharing_apps",

    "face unlock or facial recognition apps": "facial_recognition",
    "smartphone camera features": "smartphone_camera",

    "messaging apps": "messaging_apps",
    "social media platforms": "social_media_platforms",
    "video conferencing tools": "video_conferencing_tools",
    
    "product/content recommendation platforms": "recommendation platforms",

    "web browsers": "web_browsers",
    "search engines": "search_engines",
    "i dont really know": "none",
    "i would choose multiple of the above given options": "none",
    "none of the above": "none",
}

education_map = {
    "bachelor's degree" : "bachelors",
    "high school" : "high_school",
    "lower secondary" : "under_highschool",
    "prefer not to say" : "no_education/unspecified",
    "middle school" : "under_highschool",
    "8 class" : "under_highschool",
    "class 8" : "under_highschool",
    "diploma" : "bachelors",
    "ca , cap 3" : "bachelors",
    "master's degree" : "masters",
    "bachelor running" : "bachelors",
    "phd persuing" : "above_masters/phd",
    "doctorate degree" : "above_masters/phd",
    "computer engineering" : "bachelors",
}

benefit_to_country_map = {
    "job creation": "job creation",
    "better education opportunities": "better education opportunities",
    "faster or more efficient public services": "faster or more efficient public services",
    "improved access to healthcare": "improved access to healthcare",
    "improved safety or disaster response": "improved safety or disaster response",
    "economic development": "economic development",
}

concerns_about_ai_map = {
    "loss of jobs": "loss of jobs",
    "invasion of privacy": "invasion of privacy",
    "spread of misinformation": "spread of misinformation",
    "over-dependence on technology": "overdependence on technology",
    "bias or discrimination in decisions": "bias or discrimination in decisions",
}

residence_type_map = {
    "urban" : "urban",
    "suburban" : "suburban",
    "rural" : "rural",
    "municipality" : "suburban",
    "city" : "urban",
    "mahendranagar, kanchanpur , nepal" : "suburban"
}

raw_occupation_map = {
    # student variants
    "student": "student",
    "student m": "student",
    "student rn": "student",
    "student we": "student",
    "as student": "student",
    "student right now": "student",
    "i'm a student": "student",
    "i am a student": "student",
    "i am an student": "student",
    "bachelor student": "student",
    "bachelor's student": "student",
    "student (still studying)": "student",
    "currently studying": "student",
    "studying right now": "student",
    "studying": "student",
    "study": "student",
    "engineering student": "student",
    "it student": "student",
    "architect student": "student",
    "work as a student": "student",
    "iam undergraduate student": "student",
    "student{ ioe pulchowk campus, computer engineering}": "student",
    "student{ioe pulchowk campus, computer engineering)": "student",
    "student, web3 dev": "student",
    "youth educator and an it student": "student",
    "student and housewife": "student",
    "student and teaching": "student",
    "studenr": "student",
    "studient": "student",
    "my occupation is a student": "student",
    "nothing i am a student": "student",
    "student now": "student",
    "student /entrepreneur": "student",
    "student (undergraduate engineer)": "student",
    "not working yet, student": "student",
    "currently i am student pursuing bachelor degree on civil engineering": "student",
    "student but also a genai engineering intern": "student",
    "csit": "student",
    "csit(student)": "student",
    "student and tutor": "student",
    "i am a student, bro": "student",
    "i am an undergraduate student": "student",
    "educational youtuber and student": "student",
    "learning": "student",
    "ca student": "student",
    "undergraduate student": "student",
    "im a student": "student",

    # unemployed / no occupation
    "unemployed": "unemployed",
    "not working": "unemployed",
    "no occupation": "unemployed",
    "i dont work right now": "unemployed",
    "i don't work right now": "unemployed",
    "nothing": "unemployed",
    "null": "unemployed",
    "not": "unemployed",
    "not yet working": "unemployed",
    "no": "unemployed",
    "no occupation till now": "unemployed",
    "not employed yet": "unemployed",
    "not done yet": "unemployed",
    "na": "unemployed",
    "berojgar": "unemployed",
    "jobless": "unemployed",
    "not yet": "unemployed",
    "right now nothing": "unemployed",

    # unclear / no real info given
    "job": "job",
    "part time job": "part time job",
    "employee": "employee",

    # teaching
    "teacher": "teacher",
    "teaching": "teaching",
    "education learning": "education learning",
    "tutor": "tutor",
    "part time teacher": "part time teacher",

    # engineering / tech
    "engineering": "engineering",
    "software engineer": "software engineer",
    "software engineering": "software engineering",
    "electrical engineer": "electrical engineer",
    "civil engineer": "civil engineer",
    "developer": "developer",
    "junior machine learning engineer": "junior machine learning engineer",
    "data analyst": "data analyst",
    "data management specialist": "data management specialist",
    "cybersecurity analyst": "cybersecurity analyst",
    "security": "security",
    "seecurity operation": "security operation",
    "security operation": "security operation",
    "frontend developer": "frontend developer",
    "quality assurance analyst": "quality assurance analyst",
    "bss noc analyst": "bss noc analyst",
    "data scientist/oyo corper": "data scientist/oyo corper",
    "web developer": "web developer",
    "computer engineer": "computer engineer",
    "etl associate": "etl associate",
    "data scientist": "data scientist",
    "engineer": "engineer",
    "data science intern": "data science intern",

    # management/business
    "ceo": "ceo",
    "digital project manager": "digital project manager",
    "office manager": "office manager",
    "brand manager": "brand manager",
    "opd coordinator": "opd coordinator",
    "shipping coordinator": "shipping coordinator",
    "entrepreneur": "entrepreneur",
    "enterpreneur": "entrepreneur",
    "business": "business",
    "banking sector": "banking sector",
    "accounting": "accounting",
    "printing": "printing",
    "auditors": "auditors",
    "accountant": "accountant",
    "supervisor": "supervisor",

    # medical
    "doctor": "doctor",
    "nurse": "nurse",
    "nursing": "nursing",
    "pharmacist": "pharmacist",
    "becoming ayurvedic doctor": "becoming ayurvedic doctor",

    # misc professional / other
    "i'm a team leader in customer service": "i'm a team leader in customer service",
    "research intern": "research intern",
    "researcher": "researcher",
    "social worker": "social worker",
    "counsellor": "counsellor",
    "self employed": "self employed",
    "self-employed": "self employed",
    "graphic designer": "graphic designer",
    "graphics designer and video editor": "graphics designer and video editor",
    "architect": "architect",
    "customer service representative": "customer service representative",
    "freelancer and network marketer": "freelancer and network marketer",
    "video editor": "video editor",
    "graphic and product designer": "graphic and product designer",
    "aviation safety officer": "aviation safety officer",
    "sales assistant": "sales assistant",
    "sales": "sales",
}

raw_industry_map = {
    # Education
    "education": "education",
    "student": "student",
    "student in it": "student in it",
    "i am an student": "i am an student",
    "student right now": "student right now",
    "studying": "studying",
    "i am a student": "i am a student",
    "currently the student": "currently the student",

    # IT
    "tech": "tech",
    "it": "it",
    "data management": "data management",
    "telecommunication": "telecommunication",

    # Government / Public
    "public/government": "public/government",
    "government": "government",
    "public service": "public service",
    "environment": "environment",
    "ngo": "ngo",

    # Healthcare
    "healthcare": "healthcare",
    "health": "health",
    "health ": "health",
    "hospital": "hospital",
    "medicine": "medicine",
    "dentistry": "dentistry",
    "doctor": "doctor",
    "medical": "medical",

    # Finance / Trade
    "finance/trade": "finance/trade",
    "financial": "financial",
    "trading": "trading",
    "e-commerce": "e-commerce",
    "fmcg food product import": "fmcg food product import",

    # Production / Manufacturing
    "production/manufacturing": "production/manufacturing",
    "manufacturing": "manufacturing",
    "processing": "processing",
    "agriculture": "agriculture",
    "construction": "construction",
    "automobile": "automobile",

    # None / Other
    "none/other": "none/other",
    "engineering": "engineering",
    "engineering ": "engineering",
    "archi": "archi",
    "architecture": "architecture",
    "transport industry": "transport industry",
    "none as of right now": "none as of right now",
    "nothing": "nothing",
    "not working": "not working",
    "not yet working": "not yet working",
    "beauty": "beauty",
    "unemployed": "unemployed",
    "civil engineering": "civil engineering",
    "aviation": "aviation",
    "consulting services": "consulting services",
    "": "",
}
