occupation_map = {
    # student variants
    "student": "student",
    "students": "student",
    "student m": "student",
    "student rn": "student",
    "student we": "student",
    "as student": "student",
    "student right now": "student",
    "student right now.": "student",
    "i'm a student": "student",
    "i am a student": "student",
    "bachelor student": "student",
    "bachelor's student": "student",
    "student (still studying)": "student",
    "currently studying": "student",
    "studying right now": "student",
    "studying": "student",
    "study": "student",
    "engineering student": "student",
    "it student": "student",
    "architect student": "student",
    "work as a student": "student",
    "iam undergraduate student": "student",
    "student{ ioe pulchowk campus, computer engineering}": "student",
    "student{ioe pulchowk campus, computer engineering)": "student",
    "student, web3 dev": "student",
    "youth educator and an it student": "student",
    "student and housewife": "student",
    "student and teaching": "student",
    "studenr" : "student",

    # unemployed / no occupation
    "unemployed": "unemployed",
    "not working": "unemployed",
    "no occupation": "unemployed",
    "i dont work right now.": "unemployed",
    "i don't work right now.": "unemployed",
    "nothing": "unemployed",
    "null": "unemployed",
    "not": "unemployed",
    "job": "unemployed",  # ambiguous/no-info, treat as unusable/unclear

    # teaching
    "teacher": "teacher",
    "teaching": "teacher",
    "education learning": "teacher",

    # engineering / tech
    "engineering": "engineering/tech",
    "software engineer": "engineering/tech",
    "software engineering": "engineering/tech",
    "electrical engineer": "engineering/tech",
    "civil engineer": "engineering/tech",
    "developer": "engineering/tech",
    "junior machine learning engineer": "engineering/tech",
    "data analyst": "engineering/tech",
    "data management specialist": "engineering/tech",
    "cybersecurity analyst": "engineering/tech",
    "security": "engineering/tech",
    "seecurity operation": "engineering/tech",
    "security operation": "engineering/tech",

    # management/business
    "ceo": "management/business",
    "digital project manager": "management/business",
    "office manager": "management/business",
    "brand manager": "management/business",
    "opd coordinator": "management/business",
    "shipping coordinator": "management/business",
    "entrepreneur": "management/business",
    "enterpreneur": "management/business",
    "business": "management/business",
    "employee": "management/business",
    "banking sector": "management/business",
    "accounting": "management/business",
    "printing": "management/business",
    "part time job": "management/business",

    # medical
    "doctor": "medical",
    "nurse": "medical",
    "nursing": "medical",
    "pharmacist": "medical",

    # misc professional
    "i'm a team leader in customer service": "other",
    "research intern": "other",
    "researcher": "other",
    "social worker": "other",
    "counsellor": "other",
    "self employed": "other",
    "self-employed": "other",
    "graphic designer": "other",
    "graphics designer and video editor": "other",
}

ethnicity_map = {
    "asian" : "asian",
    "african" : "african/non-asian",
    "american indian" : "asian",
    "latino" : "african/non-asian",
    "nepali" : "asian",
    "black african/african american" : "african/non-asian",
    "indian" : "asian",
    "bramin" : "asian",
}

language_map = {
    "english": "english", "english.": "english", ".english":"english", "little bit english" : "english", "little" : "english", "bit" : "english",
    "hindi": "south_asian_other", "hindni": "south_asian_other", ".hindi":"south_asian_other",
    "arabic": "global_other", "arebic": "global_other",
    "bajika": "south_asian_other",
    "bhojpuri": "south_asian_other", "bojpuri": "south_asian_other",
    "chinese": "global_other",
    "dotali": "nepali_dominant", "doteli": "nepali_dominant",
    "efik": "african_other",
    "ekoi": "african_other",
    "french": "global_other",
    "greek": "global_other",
    "gurung": "nepali_dominant",
    "hausa": "african_other", "hausa.": "african_other",
    "ibibio": "african_other",
    "igbo": "african_other",
    "japanese": "global_other",
    "korean": "global_other",
    "latin": "global_other",
    "madheshi": "nepali_dominant",
    "magar": "nepali_dominant",
    "maithali": "south_asian_other", "maithili": "south_asian_other", "maithilils": "south_asian_other",
    "maithli": "south_asian_other", "mathali": "south_asian_other", "mathi": "south_asian_other",
    "marwadi": "south_asian_other",
    "nep": "nepali_dominant", "nepal": "nepali_dominant", "nepali": "nepali_dominant",
    "neplai": "nepali_dominant", "neplit": "nepali_dominant", "neoali": "nepali_dominant",
    "newari": "nepali_dominant",
    "pahadi": "nepali_dominant",
    "pidgin": "global_other",
    "rai": "nepali_dominant",
    "sanskrit": "nepali_dominant",
    "spanish": "global_other",
    "swahili": "african_other",
    "tharu": "nepali_dominant",
    "urdu": "south_asian_other",
    "yoruba": "african_other",
    "lokurr" : "african_other",
    "tapa" : "african_other",
    "and": "",
    "nah": "",
    "awadhi": "south_asian_other",
}

region_map = {
    "nepal" : "nepal",
    "nigeria" : "africa_other",
    "united kingdom" : "global",
    "saudi arabia" : "asia_other",
    "united states" : "global",
    "india" : "asia_other",
    "tanzania" : "africa_other",
    "estonia" : "global",
    "qatar" : "asia_other",
}

ordinal_maps = {
    "internet_usage_frequency": {
        "never": 1,
        "yearly": 2,
        "weekly": 3,
        "daily": 4,
    },
    "daily_ai_exposure": {
        "never": 1,
        "seasonal": 2,
        "monthly": 3,
        "weekly": 4,
        "daily": 5,
    },
    "computer_proficiency": {
        "not proficient  i struggle with using computers and only use them when absolutely necessary, usually with assistance.": 1,
        "limited proficiency  i can do simple tasks with guidance, but i often need help and do not feel confident using computers independently.": 2,
        "moderately proficient  i can perform basic tasks like browsing the internet, sending emails, and using office software, but i may need help with more complex problems.": 3,
        "proficient  i am comfortable using computers for most tasks such as browsing, word processing, and using common applications. i can solve minor issues on my own.": 4,
        "very proficient  i am highly skilled with computers, including software, internet use, and troubleshooting. i can easily learn new programs and help others.": 5,
    },
    "ai_familiarity": {
        "not at all familiar": 1,
        "slightly familiar": 2,
        "moderately familiar": 3,
        "very familiar": 4,
        "extremely familiar": 5,
    },
    "confidence_understanding_ai": {
        "extremely not confident": 1,
        "somewhat not confident": 2,
        "neutral": 3,
        "somewhat confident": 4,
        "extremely confident": 5,
    },
    "general_feeling_about_ai": {
        "very negative": 1,
        "somewhat negative": 2,
        "neutral": 3,
        "somewhat positive": 4,
        "very positive": 5,
    },
    "future_ai_impact": {
        "no impact": 1,
        "slight impact": 2,
        "moderate impact": 3,
        "significant impact": 4,
        "extremely significant impact": 5,
    },
    "current_ai_impact_on_daily_life": {
        "not at all": 1,
        "a little": 2,
        "somewhat": 3,
        "quite a lot": 4,
        "very much": 5,
    },
    "awareness_of_ai_usage": {
        "never": 1,
        "rarely": 2,
        "sometimes": 3,
        "often": 4,
        "always": 5,
        "i dont know": 0,
    },
    "trust_ai_healthcare": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_insurance": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_agriculture": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_finance": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_military": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_law_enforcement": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_environment": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_education": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_transportation": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_manufacturing": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_human_resources": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "trust_ai_remittance": {
        "strongly disapprove": 1,
        "disapprove": 2,
        "neutral / no opinion": 3,
        "approve": 4,
        "strongly approve": 5,
    },
    "accept_ai_hiring": {
        "not at all comfortable": 1,
        "not very comfortable": 2,
        "neutral": 3,
        "fairly comfortable": 4,
        "very comfortable": 5,
    },
    "accept_ai_energy_meter": {
        "not at all comfortable": 1,
        "not very comfortable": 2,
        "neutral": 3,
        "fairly comfortable": 4,
        "very comfortable": 5,
    },
    "support_national_ai_laws": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_voluntary_ai_certification": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_independent_ai_monitoring": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_company_self_regulation": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_ai_transparency": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_diverse_ai_development": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "trust_national_government": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_international_bodies": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_universities": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_consumer_groups": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_tech_companies": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_social_media_companies": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "support_national_ai_policies": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_ai_local_language_education": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_public_private_partnerships": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_rural_internet": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "support_ai_literacy": {
        "not important at all": 1,
        "of little importance": 2,
        "moderately important": 3,
        "important": 4,
        "very important": 5,
    },
    "trust_national_government_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_local_tech_companies_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_international_ngos_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_academic_institutions_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_cooperative_societies_to_lead_ai": {
        "not at all": 1,
        "slightly": 2,
        "moderately": 3,
        "mostly": 4,
        "completely": 5,
    },
    "trust_domestic_ai_more": {
        "not at all": 1,
        "not so much": 2,
        "so and so": 3,
        "somewhat": 4,
        "a lot": 5,
    },
    "perceived_ai_impact_after_survey": {
        "not at all": 1,
        "not so much": 2,
        "so and so": 3,
        "somewhat": 4,
        "a lot": 5,
    },
    "have_government_policy_to_guide_ai_development":{
        "strongly disagree": 1,
        "disagree": 2,
        "neither agree nor disagree": 3,
        "agree": 4,
        "strongly agree": 5,
    }
}

industry_map = {
    # Education
    "education": "education",
    "student": "education",
    "student in it": "education",

    # IT
    "it (information technology)": "tech",
    "data management": "tech",

    # Government / Public
    "government": "public/government",
    "public service": "public/government",

    # Healthcare
    "health": "healthcare",
    "health ": "healthcare",     
    "hospital": "healthcare",
    "medicine": "healthcare",
    "dentistry": "healthcare",

    # Finance
    "financial": "finance/trade",

    # Engineering
    "engineering": "none/other",
    "engineering ": "none/other",
    "archi": "none/other",
    "processing" : "none/other",

    # Telecommunications
    "telecommunication": "tech",

    # Manufacturing
    "manufacturing": "production/manufacturing",
    "processing": "production/manufacturing",

    # Agriculture
    "agriculture": "production/manufacturing",

    # Transportation
    "transport industry": "none/other",

    # Trade
    "trading": "finance/trade",

    # Environment
    "environment": "public/government",

    # NGOs
    "ngo": "public/government",

    # Unemployed / none
    "none as of right now": "none/other",
    "nothing": "none/other",
}

ai_tools_map = {
    "ai in agriculture" : "agriculture",
    "chat gpt and gemini" : "gen_ai/chatbot",
    "chat gpt, gemini etc" : "gen_ai/chatbot",
    "chatgpt, deepseek" : "gen_ai/chatbot",
    "chatgpt, meta ai" : "gen_ai/chatbot",
    "customer service chatbots" : "gen_ai/chatbot",
    "digital payment platforms" : "finance",
    "education , and ai for content generation and image creation" : "gen_ai/chatbot",
    "fraud detection systems" : "finance",
    "graphic design applications like canva" : "gen_ai/chatbot",
    "healthcare tools" : "healthcare",
    "no now" : "",
    "openai embeddings, llms such as chatgpt and github copilot" : "gen_ai/chatbot",
    "openai like chargpt." : "gen_ai/chatbot",
    "product or content recommendation systems" : "product/recommendation_system",
    "ride-hailing or delivery apps" : "product/recommendation_system",
    "social media platforms using ai" : "socialmedia/app",
}

app_use_ai_map = {
    "calculators" : "productivity/office",
    "calendar apps" : "productivity/office",
    "drones" : "travel/mobility",
    "email spam filters" : "productivity/office",
    "face unlock or facial recognition apps" : "device_intelligence",
    "hotel booking sites" : "travel/mobility",
    "i dont really know" : "",
    "i would choose multiple of the above given options" : "",
    "messaging apps" : "socialmedia/messaging",
    "navigation apps" : "travel/mobility",
    "none of the above" : "",
    "product/content recommendation platforms" : "",
    "ride-sharing apps" : "travel/mobility",
    "search engines" : "search_engine",
    "smartphone camera features": "device_intelligence",
    "social media platforms" : "socialmedia/messaging",
    "video conferencing tools" : "socialmedia/messaging",
    "web browsers" : "search_engine",
    "word processing software" : "productivity/office",
}

education_map = {
    "bachelor's degree" : "bachelors/masters",
    "high school" : "high school",
    "master's degree" : "bachelors/masters",
    "bachelor running" : "bachelors/masters",
    "phd. persuing" : "above_masters/pdh",
    "computer engineering" : "bachelors/masters",
}

benefit_to_country_map = {
    "job creation": "job creation",
    "better education opportunities": "better education opportunities",
    "faster or more efficient public services": "faster or more efficient public services",
    "improved access to healthcare": "improved access to healthcare",
    "improved safety or disaster response": "improved safety or disaster response",
    "economic development": "economic development",
}

concerns_about_ai_map = {
    "loss of jobs": "Loss of jobs",
    "invasion of privacy": "Invasion of privacy",
    "spread of misinformation": "Spread of misinformation",
    "over-dependence on technology": "Over-dependence on technology",
    "bias or discrimination in decisions": "Bias or discrimination in decisions",
}

residence_type_map = {
    "urban" : "urban",
    "suburban" : "suburban",
    "rural" : "rural",
    "municipality" : "suburban",
    "city" : "urban",
}